---
title: Sport-Nature
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Julien
    permalink: "/:categories/:title"

email: sportBlog@sport.com
description: This is a awesome Blog about sport and Nature. But most important, it
  is a plain exercice on mastering Jekyll.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-admin
